project:
  type: website
  output-dir: docs

website:
  title: "seong/bin/blog"
  site-url: https://blog.seongbin.me
  description: "My journey to become a cool grandma"
  navbar: 
    right:
      - text: Home
        href: https://seongbin.me
      - icon: github
        href: https://github.com/se0ngbin
      - icon: linkedin
        href: "https://linkedin.com/seongbeanie"
      - icon: "{{<ai google-scholar>}}"
        href: https://scholar.google.com/citations?user=P2nTstoAAAAJ
format:
  html:
    theme: morph
    css: 
      - styles.css
      - _extensions/schochastics/academicons/assets/css/all.css



